server {
  listen 80;
  location / { try_files $uri $uri/ /index.html; }
  location /api/ { proxy_pass http://backend:8000; }
  location /users/ { proxy_pass http://backend:8000; }
  location /recommendations/ { proxy_pass http://backend:8000; }
  location /feedback { proxy_pass http://backend:8000; }
  location /analytics/ { proxy_pass http://backend:8000; }
}
